apiPackage: org.domiot.api
invokerPackage: org.domiot.invoker
modelPackage: org.domiot.model
configPackage: org.domiot.config
dateLibrary: java8-localdatetime
interfaceOnly: true
serializableModel: true
modelTests: false
useTags: true
